### ISSUE TITLE
Tokenizer breaks on "-"

### ISSUE THREAD

**Issue by dabasmoti** [YontiLevin/Hebrew-Tokenizer#4]
Hi,
The tokenizer breaks on "-" for example
"מערבית-מודרנית"
and stop tokenize the rest of the text

**Comment by YontiLevin** [comment]
thanks for the feedback

tested it and it works for me
can you please add the log?

**Comment by dabasmoti** [comment]
Sorry for the misleading,
there is no error or exceptions, it's just stop tokenize after the hyphen
but,
I have figure it out, there is strange hyphens in the text, so by adding those hyphens to

`_punc = r"[,;:\-&!\?\.\]/)'`\"\*\+=_~}\[('`\"{/\\\<\>#%־—–]"
`

here is the link to txt file, you can check it:
https://www.dropbox.com/s/pckysua4grha49n/1.8314503.txt?dl=0

**Comment by YontiLevin** [comment]
ok
i will fix it tonight and upload to pypi the fixed version
meanwhile you can download the source code and change it locally

**Comment by dabasmoti** [comment]
Thats what i did

**Comment by YontiLevin** [comment]
fixed the unknown chars handling
now it shouldn't break 
when the chars are unknown - it will return 'UNKOWN' in the group tag
