### ISSUE TITLE
Export Groups and make it an Enum

### ISSUE THREAD

**Issue by iddan** [YontiLevin/Hebrew-Tokenizer#5]
`Groups`(https://github.com/YontiLevin/Hebrew-Tokenizer/blob/master/hebrew_tokenizer/api.py#L97) is currently a class inheriting from object while it should inherit from `Enum`.

**Comment by YontiLevin** [comment]
it requires installing the enum package and i want to keep this without any additional packages

**Comment by iddan** [comment]
Enum is part of the standard library https://docs.python.org/3/library/enum.html

**Comment by YontiLevin** [comment]
added
thanks
