### ISSUE TITLE
ImportError: cannot import name 'Pattern' from 'sre_parse' with python3.8

### ISSUE THREAD

**Issue by GalMoore** [YontiLevin/Hebrew-Tokenizer#6]
Hey,

This worked fine on another system - but with my current setup I'm getting: 
`ImportError: cannot import name 'Pattern' from 'sre_parse' anaconda3/lib/python3.8/sre_parse.py)`

Could it be related to my python=3.8?
Any thoughts?
Thanks,

Gal

**Comment by YontiLevin** [comment]
Yeah, it's a python 3.8 related bug. 
I haven't tested it for versions >3.6.
will do over the weekend.

**Comment by GalMoore** [comment]
Cheers! Much appreciated

**Comment by YontiLevin** [comment]
pushed a new version that should solve it.
also uploaded a new version to pypi so you can try installing via pip.
closing this.
if this doesn't solve it for you then open again.
